"""add habit log unique constraint

Revision ID: 3ee2e3a2a7de
Revises: f71cd428c220
Create Date: 2025-08-11 20:30:48.062664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee2e3a2a7de'
down_revision = 'f71cd428c220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_log', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_habit_date', ['habit_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_log', schema=None) as batch_op:
        batch_op.drop_constraint('uix_habit_date', type_='unique')

    # ### end Alembic commands ###
